# This workflow will install Python dependencies, run tests and lint with a single version of Python

name: Lint code and test builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  lint_with_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync
    - name: Lint with ruff
      run: |
        # stop the build if there are Python syntax errors or undefined names
        source .venv/bin/activate
        ruff check --output-format github
  test_windows_exe_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv sync
    - name: Run pyinstaller to validate
      run: |
        .venv\Scripts\activate
        pyinstaller main.spec